// Function to get translated AddContents array
export const getAddContents = (t) => [
    {src: "https://linktree.sirv.com/Images/brands/music.svg", alt: "music", title: t("brandLinks.music"), p: t("brandLinks.music_description")},
    {src: "https://linktree.sirv.com/Images/brands/video.svg", alt: "video", title: t("brandLinks.video"), p: t("brandLinks.video_description")},
    {src: "https://linktree.sirv.com/Images/brands/header.svg", alt: "header", title: t("brandLinks.header"), p: t("brandLinks.header_description")},
    {src: "https://linktree.sirv.com/Images/brands/youtube.svg", alt: "youtube", title: t("brandLinks.youtube"), p: t("brandLinks.youtube_description")},
    {src: "https://linktree.sirv.com/Images/brands/spotify.svg", alt: "spotify", title: t("brandLinks.spotify"), p: t("brandLinks.spotify_description")},
    {src: "https://linktree.sirv.com/Images/brands/pinterest.svg", alt: "pinterest", title: t("brandLinks.pinterest"), p: t("brandLinks.pinterest_description")},
    {src: "https://linktree.sirv.com/Images/brands/twitter.svg", alt: "twitter", title: t("brandLinks.twitter"), p: t("brandLinks.twitter_description")},
    {src: "https://linktree.sirv.com/Images/brands/reddit.svg", alt: "reddit", title: t("brandLinks.reddit"), p: t("brandLinks.reddit_description")},
    {src: "https://linktree.sirv.com/Images/brands/tiktok.svg", alt: "tiktok", title: t("brandLinks.tiktok_profile"), p: t("brandLinks.tiktok_description")},
    {src: "https://linktree.sirv.com/Images/brands/audiomack.svg", alt: "audiomack", title: t("brandLinks.audiomack"), p: t("brandLinks.audiomack_description")},
];


export const baseUrlIcons = {
  // Existing entries
  'vm.tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'www.tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'm.tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'audiomack.com': 'https://linktree.sirv.com/Images/brands/audiomack.svg',
  'www.audiomack.com': 'https://linktree.sirv.com/Images/brands/audiomack.svg',
  'twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'www.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'mobile.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'es.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'fr.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'jp.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'github.com': 'https://linktree.sirv.com/Images/brands/github.svg',
  'www.github.com': 'https://linktree.sirv.com/Images/brands/github.svg',
  'www.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'in.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'fr.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'es.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'open.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'play.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'i.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'd.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'www.youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'm.youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'studio.youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'www.reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'old.reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'new.reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'www.paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'www.sandbox.paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'sandbox.paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'www.paypal.me': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'paypal.me': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'www.instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'i.instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'm.instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'www.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'web.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'mobile.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'i.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'm.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'tr.ee': 'https://linktree.sirv.com/Images/brands/Linktree.svg',
  'www.linktr.ee': 'https://linktree.sirv.com/Images/brands/Linktree.svg',
  'linktr.ee': 'https://linktree.sirv.com/Images/brands/Linktree.svg',
  'www.threads.net': 'https://linktree.sirv.com/Images/brands/Threads.svg',
  'threads.net': 'https://linktree.sirv.com/Images/brands/Threads.svg',
  'wa.me': 'https://linktree.sirv.com/Images/brands/whatsapp.svg',
  'wa.link': 'https://linktree.sirv.com/Images/brands/whatsapp.svg',
  'web.whatsapp.com': 'https://linktree.sirv.com/Images/brands/whatsapp.svg',
  'co.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'www.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'www.pinterest.co.uk': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'in.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'www.pinterest.ca': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'br.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'au.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'fr.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'mx.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'de.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'es.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'it.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'co.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'www.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'www.medium.co.uk': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'in.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'www.medium.ca': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'br.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'au.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'fr.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'mx.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'de.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'es.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'it.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'fabiconcept.online': 'https://linktree.sirv.com/Images/icons/me.gif',

  // Music Platforms
  'music.apple.com': 'https://www.google.com/s2/favicons?domain=music.apple.com&sz=32',
  'music.youtube.com': 'https://favicon.is/music.youtube.com',
  'soundcloud.com': 'https://favicon.is/soundcloud.com',
  'www.soundcloud.com': 'https://favicon.is/soundcloud.com',
  'm.soundcloud.com': 'https://favicon.is/soundcloud.com',
  'on.soundcloud.com': 'https://favicon.is/soundcloud.com',
  'bandcamp.com': 'https://favicon.is/bandcamp.com',
  'www.bandcamp.com': 'https://favicon.is/bandcamp.com',
  'tidal.com': 'https://favicon.is/tidal.com',
  'www.tidal.com': 'https://favicon.is/tidal.com',
  'listen.tidal.com': 'https://favicon.is/tidal.com',
  'deezer.com': 'https://favicon.is/deezer.com',
  'www.deezer.com': 'https://favicon.is/deezer.com',
  'pandora.com': 'https://favicon.is/pandora.com',
  'www.pandora.com': 'https://favicon.is/pandora.com',
  'music.amazon.com': 'https://favicon.is/music.amazon.com',
  'amazon.music': 'https://favicon.is/music.amazon.com',

  // Video Platforms
  'vimeo.com': 'https://favicon.is/vimeo.com',
  'www.vimeo.com': 'https://favicon.is/vimeo.com',
  'player.vimeo.com': 'https://favicon.is/vimeo.com',
  'twitch.tv': 'https://favicon.is/twitch.tv',
  'www.twitch.tv': 'https://favicon.is/twitch.tv',
  'm.twitch.tv': 'https://favicon.is/twitch.tv',
  'go.twitch.tv': 'https://favicon.is/twitch.tv',
  'kick.com': 'https://favicon.is/kick.com',
  'www.kick.com': 'https://favicon.is/kick.com',
  'dailymotion.com': 'https://favicon.is/dailymotion.com',
  'www.dailymotion.com': 'https://favicon.is/dailymotion.com',
  'rumble.com': 'https://favicon.is/rumble.com',
  'www.rumble.com': 'https://favicon.is/rumble.com',

  // Social Media
  'x.com': 'https://favicon.is/x.com',
  'www.x.com': 'https://favicon.is/x.com',
  'snapchat.com': 'https://favicon.is/snapchat.com',
  'www.snapchat.com': 'https://favicon.is/snapchat.com',
  'web.snapchat.com': 'https://favicon.is/snapchat.com',
  'discord.com': 'https://favicon.is/discord.com',
  'www.discord.com': 'https://favicon.is/discord.com',
  'discord.gg': 'https://favicon.is/discord.com',
  'telegram.org': 'https://favicon.is/telegram.org',
  'www.telegram.org': 'https://favicon.is/telegram.org',
  't.me': 'https://favicon.is/telegram.org',
  'web.telegram.org': 'https://favicon.is/telegram.org',
  'signal.org': 'https://favicon.is/signal.org',
  'www.signal.org': 'https://favicon.is/signal.org',
  'clubhouse.com': 'https://favicon.is/clubhouse.com',
  'www.clubhouse.com': 'https://favicon.is/clubhouse.com',
  'mastodon.social': 'https://favicon.is/mastodon.social',
  'joinmastodon.org': 'https://favicon.is/mastodon.social',
  'tumblr.com': 'https://favicon.is/tumblr.com',
  'www.tumblr.com': 'https://favicon.is/tumblr.com',
  'flickr.com': 'https://favicon.is/flickr.com',
  'www.flickr.com': 'https://favicon.is/flickr.com',
  '500px.com': 'https://favicon.is/500px.com',
  'www.500px.com': 'https://favicon.is/500px.com',
  'deviantart.com': 'https://favicon.is/deviantart.com',
  'www.deviantart.com': 'https://favicon.is/deviantart.com',
  'behance.net': 'https://favicon.is/behance.net',
  'www.behance.net': 'https://favicon.is/behance.net',
  'dribbble.com': 'https://favicon.is/dribbble.com',
  'www.dribbble.com': 'https://favicon.is/dribbble.com',

  // Professional Networks
  'xing.com': 'https://favicon.is/xing.com',
  'www.xing.com': 'https://favicon.is/xing.com',
  'glassdoor.com': 'https://favicon.is/glassdoor.com',
  'www.glassdoor.com': 'https://favicon.is/glassdoor.com',
  'indeed.com': 'https://favicon.is/indeed.com',
  'www.indeed.com': 'https://favicon.is/indeed.com',
  'angel.co': 'https://favicon.is/angel.co',
  'www.angel.co': 'https://favicon.is/angel.co',
  'wellfound.com': 'https://favicon.is/wellfound.com',
  'www.wellfound.com': 'https://favicon.is/wellfound.com',

  // Code Platforms
  'gitlab.com': 'https://favicon.is/gitlab.com',
  'www.gitlab.com': 'https://favicon.is/gitlab.com',
  'about.gitlab.com': 'https://favicon.is/gitlab.com',
  'bitbucket.org': 'https://favicon.is/bitbucket.org',
  'www.bitbucket.org': 'https://favicon.is/bitbucket.org',
  'sourceforge.net': 'https://favicon.is/sourceforge.net',
  'www.sourceforge.net': 'https://favicon.is/sourceforge.net',
  'codepen.io': 'https://favicon.is/codepen.io',
  'www.codepen.io': 'https://favicon.is/codepen.io',
  'codesandbox.io': 'https://favicon.is/codesandbox.io',
  'www.codesandbox.io': 'https://favicon.is/codesandbox.io',
  'replit.com': 'https://favicon.is/replit.com',
  'www.replit.com': 'https://favicon.is/replit.com',
  'stackblitz.com': 'https://favicon.is/stackblitz.com',
  'www.stackblitz.com': 'https://favicon.is/stackblitz.com',
  'stackoverflow.com': 'https://favicon.is/stackoverflow.com',
  'www.stackoverflow.com': 'https://favicon.is/stackoverflow.com',
  'stackexchange.com': 'https://favicon.is/stackexchange.com',
  'www.stackexchange.com': 'https://favicon.is/stackexchange.com',
  'codechef.com': 'https://favicon.is/codechef.com',
  'www.codechef.com': 'https://favicon.is/codechef.com',
  'codeforces.com': 'https://favicon.is/codeforces.com',
  'www.codeforces.com': 'https://favicon.is/codeforces.com',
  'hackerrank.com': 'https://favicon.is/hackerrank.com',
  'www.hackerrank.com': 'https://favicon.is/hackerrank.com',
  'leetcode.com': 'https://favicon.is/leetcode.com',
  'www.leetcode.com': 'https://favicon.is/leetcode.com',

  // Learning Platforms
  'coursera.org': 'https://favicon.is/coursera.org',
  'www.coursera.org': 'https://favicon.is/coursera.org',
  'edx.org': 'https://favicon.is/edx.org',
  'www.edx.org': 'https://favicon.is/edx.org',
  'udemy.com': 'https://favicon.is/udemy.com',
  'www.udemy.com': 'https://favicon.is/udemy.com',
  'udacity.com': 'https://favicon.is/udacity.com',
  'www.udacity.com': 'https://favicon.is/udacity.com',
  'khanacademy.org': 'https://favicon.is/khanacademy.org',
  'www.khanacademy.org': 'https://favicon.is/khanacademy.org',
  'pluralsight.com': 'https://favicon.is/pluralsight.com',
  'www.pluralsight.com': 'https://favicon.is/pluralsight.com',
  'skillshare.com': 'https://favicon.is/skillshare.com',
  'www.skillshare.com': 'https://favicon.is/skillshare.com',
  'masterclass.com': 'https://favicon.is/masterclass.com',
  'www.masterclass.com': 'https://favicon.is/masterclass.com',
  'lynda.com': 'https://favicon.is/lynda.com',
  'www.lynda.com': 'https://favicon.is/lynda.com',
  'linkedin.com/learning': 'https://favicon.is/linkedin.com',

  // Shopping & E-commerce
  'amazon.com': 'https://favicon.is/amazon.com',
  'www.amazon.com': 'https://favicon.is/amazon.com',
  'amazon.co.uk': 'https://favicon.is/amazon.com',
  'amazon.ca': 'https://favicon.is/amazon.com',
  'amazon.de': 'https://favicon.is/amazon.com',
  'amazon.fr': 'https://favicon.is/amazon.com',
  'amazon.it': 'https://favicon.is/amazon.com',
  'amazon.es': 'https://favicon.is/amazon.com',
  'amazon.in': 'https://favicon.is/amazon.com',
  'amazon.com.br': 'https://favicon.is/amazon.com',
  'ebay.com': 'https://favicon.is/ebay.com',
  'www.ebay.com': 'https://favicon.is/ebay.com',
  'etsy.com': 'https://favicon.is/etsy.com',
  'www.etsy.com': 'https://favicon.is/etsy.com',
  'shopify.com': 'https://favicon.is/shopify.com',
  'www.shopify.com': 'https://favicon.is/shopify.com',
  'aliexpress.com': 'https://favicon.is/aliexpress.com',
  'www.aliexpress.com': 'https://favicon.is/aliexpress.com',
  'alibaba.com': 'https://favicon.is/alibaba.com',
  'www.alibaba.com': 'https://favicon.is/alibaba.com',
  'wish.com': 'https://favicon.is/wish.com',
  'www.wish.com': 'https://favicon.is/wish.com',

  // News & Blogs
  'substack.com': 'https://favicon.is/substack.com',
  'www.substack.com': 'https://favicon.is/substack.com',
  'hashnode.com': 'https://favicon.is/hashnode.com',
  'www.hashnode.com': 'https://favicon.is/hashnode.com',
  'dev.to': 'https://favicon.is/dev.to',
  'www.dev.to': 'https://favicon.is/dev.to',
  'hackernoon.com': 'https://favicon.is/hackernoon.com',
  'www.hackernoon.com': 'https://favicon.is/hackernoon.com',
  'wordpress.com': 'https://favicon.is/wordpress.com',
  'www.wordpress.com': 'https://favicon.is/wordpress.com',
  'wordpress.org': 'https://favicon.is/wordpress.org',
  'www.wordpress.org': 'https://favicon.is/wordpress.org',
  'ghost.org': 'https://favicon.is/ghost.org',
  'www.ghost.org': 'https://favicon.is/ghost.org',
  'blogger.com': 'https://favicon.is/blogger.com',
  'www.blogger.com': 'https://favicon.is/blogger.com',
  'wix.com': 'https://favicon.is/wix.com',
  'www.wix.com': 'https://favicon.is/wix.com',
  'squarespace.com': 'https://favicon.is/squarespace.com',
  'www.squarespace.com': 'https://favicon.is/squarespace.com',

  // Messaging & Communication
  'slack.com': 'https://favicon.is/slack.com',
  'www.slack.com': 'https://favicon.is/slack.com',
  'app.slack.com': 'https://favicon.is/slack.com',
  'teams.microsoft.com': 'https://favicon.is/teams.microsoft.com',
  'www.microsoft.com/teams': 'https://favicon.is/teams.microsoft.com',
  'zoom.us': 'https://favicon.is/zoom.us',
  'www.zoom.us': 'https://favicon.is/zoom.us',
  'us02web.zoom.us': 'https://favicon.is/zoom.us',
  'meet.google.com': 'https://favicon.is/meet.google.com',
  'hangouts.google.com': 'https://favicon.is/meet.google.com',
  'skype.com': 'https://favicon.is/skype.com',
  'www.skype.com': 'https://favicon.is/skype.com',
  'web.skype.com': 'https://favicon.is/skype.com',

  // Cloud Storage & Productivity
  'drive.google.com': 'https://favicon.is/drive.google.com',
  'docs.google.com': 'https://favicon.is/docs.google.com',
  'sheets.google.com': 'https://favicon.is/sheets.google.com',
  'slides.google.com': 'https://favicon.is/slides.google.com',
  'dropbox.com': 'https://favicon.is/dropbox.com',
  'www.dropbox.com': 'https://favicon.is/dropbox.com',
  'onedrive.live.com': 'https://favicon.is/onedrive.live.com',
  'www.onedrive.com': 'https://favicon.is/onedrive.live.com',
  'icloud.com': 'https://favicon.is/icloud.com',
  'www.icloud.com': 'https://favicon.is/icloud.com',
  'box.com': 'https://favicon.is/box.com',
  'www.box.com': 'https://favicon.is/box.com',
  'notion.so': 'https://favicon.is/notion.so',
  'www.notion.so': 'https://favicon.is/notion.so',
  'airtable.com': 'https://favicon.is/airtable.com',
  'www.airtable.com': 'https://favicon.is/airtable.com',
  'trello.com': 'https://favicon.is/trello.com',
  'www.trello.com': 'https://favicon.is/trello.com',
  'asana.com': 'https://favicon.is/asana.com',
  'www.asana.com': 'https://favicon.is/asana.com',
  'monday.com': 'https://favicon.is/monday.com',
  'www.monday.com': 'https://favicon.is/monday.com',

  // Gaming
  'steam.com': 'https://favicon.is/steam.com',
  'store.steampowered.com': 'https://favicon.is/steam.com',
  'steamcommunity.com': 'https://favicon.is/steam.com',
  'epic.games': 'https://favicon.is/epicgames.com',
  'store.epicgames.com': 'https://favicon.is/epicgames.com',
  'www.epicgames.com': 'https://favicon.is/epicgames.com',
  'battle.net': 'https://favicon.is/battle.net',
  'www.battle.net': 'https://favicon.is/battle.net',
  'origin.com': 'https://favicon.is/origin.com',
  'www.origin.com': 'https://favicon.is/origin.com',
  'uplay.com': 'https://favicon.is/uplay.com',
  'www.uplay.com': 'https://favicon.is/uplay.com',
  'itch.io': 'https://favicon.is/itch.io',
  'www.itch.io': 'https://favicon.is/itch.io',
  'gog.com': 'https://favicon.is/gog.com',
  'www.gog.com': 'https://favicon.is/gog.com',

  // Finance & Crypto
  'coinbase.com': 'https://favicon.is/coinbase.com',
  'www.coinbase.com': 'https://favicon.is/coinbase.com',
  'pro.coinbase.com': 'https://favicon.is/coinbase.com',
  'binance.com': 'https://favicon.is/binance.com',
  'www.binance.com': 'https://favicon.is/binance.com',
  'kraken.com': 'https://favicon.is/kraken.com',
  'www.kraken.com': 'https://favicon.is/kraken.com',
  'gemini.com': 'https://favicon.is/gemini.com',
  'www.gemini.com': 'https://favicon.is/gemini.com',
  'robinhood.com': 'https://favicon.is/robinhood.com',
  'www.robinhood.com': 'https://favicon.is/robinhood.com',
  'webull.com': 'https://favicon.is/webull.com',
  'www.webull.com': 'https://favicon.is/webull.com',
  'tradingview.com': 'https://favicon.is/tradingview.com',
  'www.tradingview.com': 'https://favicon.is/tradingview.com',
  'venmo.com': 'https://favicon.is/venmo.com',
  'www.venmo.com': 'https://favicon.is/venmo.com',
  'cashapp.com': 'https://favicon.is/cash.app',
  'cash.app': 'https://favicon.is/cash.app',
  'www.cash.app': 'https://favicon.is/cash.app',
  'zelle.com': 'https://favicon.is/zellepay.com',
  'www.zellepay.com': 'https://favicon.is/zellepay.com',

  // Food Delivery
  'ubereats.com': 'https://favicon.is/ubereats.com',
  'www.ubereats.com': 'https://favicon.is/ubereats.com',
  'doordash.com': 'https://favicon.is/doordash.com',
  'www.doordash.com': 'https://favicon.is/doordash.com',
  'grubhub.com': 'https://favicon.is/grubhub.com',
  'www.grubhub.com': 'https://favicon.is/grubhub.com',
  'postmates.com': 'https://favicon.is/postmates.com',
  'www.postmates.com': 'https://favicon.is/postmates.com',

  // Travel
  'airbnb.com': 'https://favicon.is/airbnb.com',
  'www.airbnb.com': 'https://favicon.is/airbnb.com',
  'booking.com': 'https://favicon.is/booking.com',
  'www.booking.com': 'https://favicon.is/booking.com',
  'expedia.com': 'https://favicon.is/expedia.com',
  'www.expedia.com': 'https://favicon.is/expedia.com',
  'hotels.com': 'https://favicon.is/hotels.com',
  'www.hotels.com': 'https://favicon.is/hotels.com',
  'trivago.com': 'https://favicon.is/trivago.com',
  'www.trivago.com': 'https://favicon.is/trivago.com',
  'kayak.com': 'https://favicon.is/kayak.com',
  'www.kayak.com': 'https://favicon.is/kayak.com',
  'skyscanner.com': 'https://favicon.is/skyscanner.com',
  'www.skyscanner.com': 'https://favicon.is/skyscanner.com',
  'uber.com': 'https://favicon.is/uber.com',
  'www.uber.com': 'https://favicon.is/uber.com',
  'lyft.com': 'https://favicon.is/lyft.com',
  'www.lyft.com': 'https://favicon.is/lyft.com',

  // Fitness & Health
  'strava.com': 'https://favicon.is/strava.com',
  'www.strava.com': 'https://favicon.is/strava.com',
  'myfitnesspal.com': 'https://favicon.is/myfitnesspal.com',
  'www.myfitnesspal.com': 'https://favicon.is/myfitnesspal.com',
  'fitbit.com': 'https://favicon.is/fitbit.com',
  'www.fitbit.com': 'https://favicon.is/fitbit.com',
  'garmin.com': 'https://favicon.is/garmin.com',
  'www.garmin.com': 'https://favicon.is/garmin.com',
  'connect.garmin.com': 'https://favicon.is/garmin.com',
  'nike.com': 'https://favicon.is/nike.com',
  'www.nike.com': 'https://favicon.is/nike.com',
  'nikeplus.com': 'https://favicon.is/nike.com',
  'adidas.com': 'https://favicon.is/adidas.com',
  'www.adidas.com': 'https://favicon.is/adidas.com',

  // Dating
  'tinder.com': 'https://favicon.is/tinder.com',
  'www.tinder.com': 'https://favicon.is/tinder.com',
  'bumble.com': 'https://favicon.is/bumble.com',
  'www.bumble.com': 'https://favicon.is/bumble.com',
  'hinge.co': 'https://favicon.is/hinge.co',
  'www.hinge.co': 'https://favicon.is/hinge.co',
  'match.com': 'https://favicon.is/match.com',
  'www.match.com': 'https://favicon.is/match.com',
  'okcupid.com': 'https://favicon.is/okcupid.com',
  'www.okcupid.com': 'https://favicon.is/okcupid.com',
  'pof.com': 'https://favicon.is/pof.com',
  'www.pof.com': 'https://favicon.is/pof.com',
  'badoo.com': 'https://favicon.is/badoo.com',
  'www.badoo.com': 'https://favicon.is/badoo.com',

  // Entertainment & Media
  'netflix.com': 'https://favicon.is/netflix.com',
  'www.netflix.com': 'https://favicon.is/netflix.com',
  'hulu.com': 'https://favicon.is/hulu.com',
  'www.hulu.com': 'https://favicon.is/hulu.com',
  'disneyplus.com': 'https://favicon.is/disneyplus.com',
  'www.disneyplus.com': 'https://favicon.is/disneyplus.com',
  'primevideo.com': 'https://favicon.is/primevideo.com',
  'www.primevideo.com': 'https://favicon.is/primevideo.com',
  'hbomax.com': 'https://favicon.is/hbomax.com',
  'www.hbomax.com': 'https://favicon.is/hbomax.com',
  'max.com': 'https://favicon.is/max.com',
  'www.max.com': 'https://favicon.is/max.com',
  'paramount.com': 'https://favicon.is/paramount.com',
  'www.paramount.com': 'https://favicon.is/paramount.com',
  'paramountplus.com': 'https://favicon.is/paramountplus.com',
  'www.paramountplus.com': 'https://favicon.is/paramountplus.com',
  'peacocktv.com': 'https://favicon.is/peacocktv.com',
  'www.peacocktv.com': 'https://favicon.is/peacocktv.com',
  'crunchyroll.com': 'https://favicon.is/crunchyroll.com',
  'www.crunchyroll.com': 'https://favicon.is/crunchyroll.com',
  'funimation.com': 'https://favicon.is/funimation.com',
  'www.funimation.com': 'https://favicon.is/funimation.com',

  // News & Information
  'wikipedia.org': 'https://favicon.is/wikipedia.org',
  'www.wikipedia.org': 'https://favicon.is/wikipedia.org',
  'en.wikipedia.org': 'https://favicon.is/wikipedia.org',
  'fr.wikipedia.org': 'https://favicon.is/wikipedia.org',
  'de.wikipedia.org': 'https://favicon.is/wikipedia.org',
  'es.wikipedia.org': 'https://favicon.is/wikipedia.org',
  'bbc.com': 'https://favicon.is/bbc.com',
  'www.bbc.com': 'https://favicon.is/bbc.com',
  'cnn.com': 'https://favicon.is/cnn.com',
  'www.cnn.com': 'https://favicon.is/cnn.com',
  'nytimes.com': 'https://favicon.is/nytimes.com',
  'www.nytimes.com': 'https://favicon.is/nytimes.com',
  'washingtonpost.com': 'https://favicon.is/washingtonpost.com',
  'www.washingtonpost.com': 'https://favicon.is/washingtonpost.com',
  'theguardian.com': 'https://favicon.is/theguardian.com',
  'www.theguardian.com': 'https://favicon.is/theguardian.com',
  'reuters.com': 'https://favicon.is/reuters.com',
  'www.reuters.com': 'https://favicon.is/reuters.com',
  'techcrunch.com': 'https://favicon.is/techcrunch.com',
  'www.techcrunch.com': 'https://favicon.is/techcrunch.com',
  'wired.com': 'https://favicon.is/wired.com',
  'www.wired.com': 'https://favicon.is/wired.com',
  'theverge.com': 'https://favicon.is/theverge.com',
  'www.theverge.com': 'https://favicon.is/theverge.com',
  'engadget.com': 'https://favicon.is/engadget.com',
  'www.engadget.com': 'https://favicon.is/engadget.com',
  'ars-technica.com': 'https://favicon.is/arstechnica.com',
  'arstechnica.com': 'https://favicon.is/arstechnica.com',

  // Design & Creative
  'figma.com': 'https://favicon.is/figma.com',
  'www.figma.com': 'https://favicon.is/figma.com',
  'adobe.com': 'https://favicon.is/adobe.com',
  'www.adobe.com': 'https://favicon.is/adobe.com',
  'creativecloud.adobe.com': 'https://favicon.is/adobe.com',
  'photoshop.adobe.com': 'https://favicon.is/adobe.com',
  'illustrator.adobe.com': 'https://favicon.is/adobe.com',
  'canva.com': 'https://favicon.is/canva.com',
  'www.canva.com': 'https://favicon.is/canva.com',
  'sketch.com': 'https://favicon.is/sketch.com',
  'www.sketch.com': 'https://favicon.is/sketch.com',
  'invisionapp.com': 'https://favicon.is/invisionapp.com',
  'www.invisionapp.com': 'https://favicon.is/invisionapp.com',
  'miro.com': 'https://favicon.is/miro.com',
  'www.miro.com': 'https://favicon.is/miro.com',
  'framer.com': 'https://favicon.is/framer.com',
  'www.framer.com': 'https://favicon.is/framer.com',
  'principle.design': 'https://favicon.is/principleformac.com',
  'principleformac.com': 'https://favicon.is/principleformac.com',
  'www.principleformac.com': 'https://favicon.is/principleformac.com',

  // Email & Communication
  'gmail.com': 'https://favicon.is/gmail.com',
  'mail.google.com': 'https://favicon.is/gmail.com',
  'outlook.com': 'https://favicon.is/outlook.com',
  'www.outlook.com': 'https://favicon.is/outlook.com',
  'outlook.live.com': 'https://favicon.is/outlook.com',
  'hotmail.com': 'https://favicon.is/outlook.com',
  'www.hotmail.com': 'https://favicon.is/outlook.com',
  'yahoo.com': 'https://favicon.is/yahoo.com',
  'mail.yahoo.com': 'https://favicon.is/yahoo.com',
  'www.yahoo.com': 'https://favicon.is/yahoo.com',
  'protonmail.com': 'https://favicon.is/protonmail.com',
  'mail.protonmail.com': 'https://favicon.is/protonmail.com',
  'www.protonmail.com': 'https://favicon.is/protonmail.com',
  'tutanota.com': 'https://favicon.is/tutanota.com',
  'www.tutanota.com': 'https://favicon.is/tutanota.com',
  'mailchimp.com': 'https://favicon.is/mailchimp.com',
  'www.mailchimp.com': 'https://favicon.is/mailchimp.com',
  'constantcontact.com': 'https://favicon.is/constantcontact.com',
  'www.constantcontact.com': 'https://favicon.is/constantcontact.com',

  // Development Tools
  'vercel.com': 'https://favicon.is/vercel.com',
  'www.vercel.com': 'https://favicon.is/vercel.com',
  'netlify.com': 'https://favicon.is/netlify.com',
  'www.netlify.com': 'https://favicon.is/netlify.com',
  'heroku.com': 'https://favicon.is/heroku.com',
  'www.heroku.com': 'https://favicon.is/heroku.com',
  'aws.amazon.com': 'https://favicon.is/aws.amazon.com',
  'console.aws.amazon.com': 'https://favicon.is/aws.amazon.com',
  'azure.microsoft.com': 'https://favicon.is/azure.microsoft.com',
  'portal.azure.com': 'https://favicon.is/azure.microsoft.com',
  'cloud.google.com': 'https://favicon.is/cloud.google.com',
  'console.cloud.google.com': 'https://favicon.is/cloud.google.com',
  'digitalocean.com': 'https://favicon.is/digitalocean.com',
  'www.digitalocean.com': 'https://favicon.is/digitalocean.com',
  'cloud.digitalocean.com': 'https://favicon.is/digitalocean.com',
  'linode.com': 'https://favicon.is/linode.com',
  'www.linode.com': 'https://favicon.is/linode.com',
  'vultr.com': 'https://favicon.is/vultr.com',
  'www.vultr.com': 'https://favicon.is/vultr.com',
  'cloudflare.com': 'https://favicon.is/cloudflare.com',
  'www.cloudflare.com': 'https://favicon.is/cloudflare.com',
  'dash.cloudflare.com': 'https://favicon.is/cloudflare.com',

  // AI & Tools
  'openai.com': 'https://favicon.is/openai.com',
  'www.openai.com': 'https://favicon.is/openai.com',
  'chat.openai.com': 'https://favicon.is/openai.com',
  'platform.openai.com': 'https://favicon.is/openai.com',
  'anthropic.com': 'https://favicon.is/anthropic.com',
  'www.anthropic.com': 'https://favicon.is/anthropic.com',
  'claude.ai': 'https://favicon.is/claude.ai',
  'www.claude.ai': 'https://favicon.is/claude.ai',
  'huggingface.co': 'https://favicon.is/huggingface.co',
  'www.huggingface.co': 'https://favicon.is/huggingface.co',
  'replicate.com': 'https://favicon.is/replicate.com',
  'www.replicate.com': 'https://favicon.is/replicate.com',
  'midjourney.com': 'https://favicon.is/midjourney.com',
  'www.midjourney.com': 'https://favicon.is/midjourney.com',
  'stability.ai': 'https://favicon.is/stability.ai',
  'www.stability.ai': 'https://favicon.is/stability.ai',
  'runwayml.com': 'https://favicon.is/runwayml.com',
  'www.runwayml.com': 'https://favicon.is/runwayml.com',

  // Search Engines
  'google.com': 'https://favicon.is/google.com',
  'www.google.com': 'https://favicon.is/google.com',
  'bing.com': 'https://favicon.is/bing.com',
  'www.bing.com': 'https://favicon.is/bing.com',
  'duckduckgo.com': 'https://favicon.is/duckduckgo.com',
  'www.duckduckgo.com': 'https://favicon.is/duckduckgo.com',
  'yahoo.com': 'https://favicon.is/yahoo.com',
  'search.yahoo.com': 'https://favicon.is/yahoo.com',
  'yandex.com': 'https://favicon.is/yandex.com',
  'www.yandex.com': 'https://favicon.is/yandex.com',
  'baidu.com': 'https://favicon.is/baidu.com',
  'www.baidu.com': 'https://favicon.is/baidu.com',
  'startpage.com': 'https://favicon.is/startpage.com',
  'www.startpage.com': 'https://favicon.is/startpage.com',
  'searx.org': 'https://favicon.is/searx.org',
  'www.searx.org': 'https://favicon.is/searx.org',

  // Alternative Social Networks
  'minds.com': 'https://favicon.is/minds.com',
  'www.minds.com': 'https://favicon.is/minds.com',
  'gab.com': 'https://favicon.is/gab.com',
  'www.gab.com': 'https://favicon.is/gab.com',
  'gettr.com': 'https://favicon.is/gettr.com',
  'www.gettr.com': 'https://favicon.is/gettr.com',
  'truthsocial.com': 'https://favicon.is/truthsocial.com',
  'www.truthsocial.com': 'https://favicon.is/truthsocial.com',
  'parler.com': 'https://favicon.is/parler.com',
  'www.parler.com': 'https://favicon.is/parler.com',
  'mewe.com': 'https://favicon.is/mewe.com',
  'www.mewe.com': 'https://favicon.is/mewe.com',

  // Forums & Communities
  'discourse.org': 'https://favicon.is/discourse.org',
  'www.discourse.org': 'https://favicon.is/discourse.org',
  'phpbb.com': 'https://favicon.is/phpbb.com',
  'www.phpbb.com': 'https://favicon.is/phpbb.com',
  'vbulletin.com': 'https://favicon.is/vbulletin.com',
  'www.vbulletin.com': 'https://favicon.is/vbulletin.com',
  'quora.com': 'https://favicon.is/quora.com',
  'www.quora.com': 'https://favicon.is/quora.com',
  'fr.quora.com': 'https://favicon.is/quora.com',
  'es.quora.com': 'https://favicon.is/quora.com',
  'de.quora.com': 'https://favicon.is/quora.com',

  // Podcasting
  'anchor.fm': 'https://favicon.is/anchor.fm',
  'www.anchor.fm': 'https://favicon.is/anchor.fm',
  'buzzsprout.com': 'https://favicon.is/buzzsprout.com',
  'www.buzzsprout.com': 'https://favicon.is/buzzsprout.com',
  'libsyn.com': 'https://favicon.is/libsyn.com',
  'www.libsyn.com': 'https://favicon.is/libsyn.com',
  'spreaker.com': 'https://favicon.is/spreaker.com',
  'www.spreaker.com': 'https://favicon.is/spreaker.com',
  'podbean.com': 'https://favicon.is/podbean.com',
  'www.podbean.com': 'https://favicon.is/podbean.com',
  'castbox.fm': 'https://favicon.is/castbox.fm',
  'www.castbox.fm': 'https://favicon.is/castbox.fm',
  'overcast.fm': 'https://favicon.is/overcast.fm',
  'www.overcast.fm': 'https://favicon.is/overcast.fm',
  'pocketcasts.com': 'https://favicon.is/pocketcasts.com',
  'www.pocketcasts.com': 'https://favicon.is/pocketcasts.com',

  // Password Managers
  'lastpass.com': 'https://favicon.is/lastpass.com',
  'www.lastpass.com': 'https://favicon.is/lastpass.com',
  '1password.com': 'https://favicon.is/1password.com',
  'www.1password.com': 'https://favicon.is/1password.com',
  'bitwarden.com': 'https://favicon.is/bitwarden.com',
  'www.bitwarden.com': 'https://favicon.is/bitwarden.com',
  'vault.bitwarden.com': 'https://favicon.is/bitwarden.com',
  'dashlane.com': 'https://favicon.is/dashlane.com',
  'www.dashlane.com': 'https://favicon.is/dashlane.com',
  'keepass.info': 'https://favicon.is/keepass.info',
  'www.keepass.info': 'https://favicon.is/keepass.info',

  // VPN Services
  'nordvpn.com': 'https://favicon.is/nordvpn.com',
  'www.nordvpn.com': 'https://favicon.is/nordvpn.com',
  'expressvpn.com': 'https://favicon.is/expressvpn.com',
  'www.expressvpn.com': 'https://favicon.is/expressvpn.com',
  'surfshark.com': 'https://favicon.is/surfshark.com',
  'www.surfshark.com': 'https://favicon.is/surfshark.com',
  'cyberghostvpn.com': 'https://favicon.is/cyberghostvpn.com',
  'www.cyberghostvpn.com': 'https://favicon.is/cyberghostvpn.com',
  'protonvpn.com': 'https://favicon.is/protonvpn.com',
  'www.protonvpn.com': 'https://favicon.is/protonvpn.com',

  // Website Builders
  'webflow.com': 'https://favicon.is/webflow.com',
  'www.webflow.com': 'https://favicon.is/webflow.com',
  'framer.com': 'https://favicon.is/framer.com',
  'bubble.io': 'https://favicon.is/bubble.io',
  'www.bubble.io': 'https://favicon.is/bubble.io',
  'editor.bubble.io': 'https://favicon.is/bubble.io',
  'carrd.co': 'https://favicon.is/carrd.co',
  'www.carrd.co': 'https://favicon.is/carrd.co',
  'jimdo.com': 'https://favicon.is/jimdo.com',
  'www.jimdo.com': 'https://favicon.is/jimdo.com',
  'weebly.com': 'https://favicon.is/weebly.com',
  'www.weebly.com': 'https://favicon.is/weebly.com',

  // Analytics & SEO
  'analytics.google.com': 'https://favicon.is/analytics.google.com',
  'www.google.com/analytics': 'https://favicon.is/analytics.google.com',
  'search.google.com': 'https://favicon.is/google.com',
  'www.google.com/webmasters': 'https://favicon.is/google.com',
  'semrush.com': 'https://favicon.is/semrush.com',
  'www.semrush.com': 'https://favicon.is/semrush.com',
  'ahrefs.com': 'https://favicon.is/ahrefs.com',
  'www.ahrefs.com': 'https://favicon.is/ahrefs.com',
  'moz.com': 'https://favicon.is/moz.com',
  'www.moz.com': 'https://favicon.is/moz.com',
  'hotjar.com': 'https://favicon.is/hotjar.com',
  'www.hotjar.com': 'https://favicon.is/hotjar.com',
  'amplitude.com': 'https://favicon.is/amplitude.com',
  'www.amplitude.com': 'https://favicon.is/amplitude.com',
  'mixpanel.com': 'https://favicon.is/mixpanel.com',
  'www.mixpanel.com': 'https://favicon.is/mixpanel.com',

  // International Social Media
  'weibo.com': 'https://favicon.is/weibo.com',
  'www.weibo.com': 'https://favicon.is/weibo.com',
  'wechat.com': 'https://favicon.is/wechat.com',
  'www.wechat.com': 'https://favicon.is/wechat.com',
  'web.wechat.com': 'https://favicon.is/wechat.com',
  'qq.com': 'https://favicon.is/qq.com',
  'www.qq.com': 'https://favicon.is/qq.com',
  'douyin.com': 'https://favicon.is/douyin.com',
  'www.douyin.com': 'https://favicon.is/douyin.com',
  'vk.com': 'https://favicon.is/vk.com',
  'www.vk.com': 'https://favicon.is/vk.com',
  'ok.ru': 'https://favicon.is/ok.ru',
  'www.ok.ru': 'https://favicon.is/ok.ru',
  'line.me': 'https://favicon.is/line.me',
  'www.line.me': 'https://favicon.is/line.me',
  'kakaotalk.com': 'https://favicon.is/kakaotalk.com',
  'www.kakaotalk.com': 'https://favicon.is/kakaotalk.com',

  // Real Estate
  'zillow.com': 'https://favicon.is/zillow.com',
  'www.zillow.com': 'https://favicon.is/zillow.com',
  'realtor.com': 'https://favicon.is/realtor.com',
  'www.realtor.com': 'https://favicon.is/realtor.com',
  'redfin.com': 'https://favicon.is/redfin.com',
  'www.redfin.com': 'https://favicon.is/redfin.com',
  'trulia.com': 'https://favicon.is/trulia.com',
  'www.trulia.com': 'https://favicon.is/trulia.com',

  // Legal & Government
  'justia.com': 'https://favicon.is/justia.com',
  'www.justia.com': 'https://favicon.is/justia.com',
  'findlaw.com': 'https://favicon.is/findlaw.com',
  'www.findlaw.com': 'https://favicon.is/findlaw.com',
  'avvo.com': 'https://favicon.is/avvo.com',
  'www.avvo.com': 'https://favicon.is/avvo.com',
  'martindale.com': 'https://favicon.is/martindale.com',
  'www.martindale.com': 'https://favicon.is/martindale.com',

  // Productivity Tools
  'todoist.com': 'https://favicon.is/todoist.com',
  'www.todoist.com': 'https://favicon.is/todoist.com',
  'any.do': 'https://favicon.is/any.do',
  'www.any.do': 'https://favicon.is/any.do',
  'wunderlist.com': 'https://favicon.is/wunderlist.com',
  'www.wunderlist.com': 'https://favicon.is/wunderlist.com',
  'evernote.com': 'https://favicon.is/evernote.com',
  'www.evernote.com': 'https://favicon.is/evernote.com',
  'onenote.com': 'https://favicon.is/onenote.com',
  'www.onenote.com': 'https://favicon.is/onenote.com',
  'simplenote.com': 'https://favicon.is/simplenote.com',
  'www.simplenote.com': 'https://favicon.is/simplenote.com',
  'bear.app': 'https://favicon.is/bear.app',
  'www.bear.app': 'https://favicon.is/bear.app',
  'obsidian.md': 'https://favicon.is/obsidian.md',
  'www.obsidian.md': 'https://favicon.is/obsidian.md',
  'roamresearch.com': 'https://favicon.is/roamresearch.com',
  'www.roamresearch.com': 'https://favicon.is/roamresearch.com',
  'logseq.com': 'https://favicon.is/logseq.com',
  'www.logseq.com': 'https://favicon.is/logseq.com',

  // Weather
  'weather.com': 'https://favicon.is/weather.com',
  'www.weather.com': 'https://favicon.is/weather.com',
  'accuweather.com': 'https://favicon.is/accuweather.com',
  'www.accuweather.com': 'https://favicon.is/accuweather.com',
  'weatherunderground.com': 'https://favicon.is/wunderground.com',
  'www.wunderground.com': 'https://favicon.is/wunderground.com',
  'weather.gov': 'https://favicon.is/weather.gov',
  'www.weather.gov': 'https://favicon.is/weather.gov',

  // Other Popular Sites
  'archive.org': 'https://favicon.is/archive.org',
  'www.archive.org': 'https://favicon.is/archive.org',
  'web.archive.org': 'https://favicon.is/archive.org',
  'imdb.com': 'https://favicon.is/imdb.com',
  'www.imdb.com': 'https://favicon.is/imdb.com',
  'rottentomatoes.com': 'https://favicon.is/rottentomatoes.com',
  'www.rottentomatoes.com': 'https://favicon.is/rottentomatoes.com',
  'metacritic.com': 'https://favicon.is/metacritic.com',
  'www.metacritic.com': 'https://favicon.is/metacritic.com',
  'goodreads.com': 'https://favicon.is/goodreads.com',
  'www.goodreads.com': 'https://favicon.is/goodreads.com',
  'audible.com': 'https://favicon.is/audible.com',
  'www.audible.com': 'https://favicon.is/audible.com',
  'kindle.amazon.com': 'https://favicon.is/amazon.com',
  'read.amazon.com': 'https://favicon.is/amazon.com',

  // Maps & Navigation
  'maps.google.com': 'https://favicon.is/maps.google.com',
  'www.google.com/maps': 'https://favicon.is/maps.google.com',
  'earth.google.com': 'https://favicon.is/earth.google.com',
  'www.google.com/earth': 'https://favicon.is/earth.google.com',
  'mapquest.com': 'https://favicon.is/mapquest.com',
  'www.mapquest.com': 'https://favicon.is/mapquest.com',
  'waze.com': 'https://favicon.is/waze.com',
  'www.waze.com': 'https://favicon.is/waze.com',
  'here.com': 'https://favicon.is/here.com',
  'www.here.com': 'https://favicon.is/here.com',
  'openstreetmap.org': 'https://favicon.is/openstreetmap.org',
  'www.openstreetmap.org': 'https://favicon.is/openstreetmap.org',

  // File Sharing & Transfer
  'wetransfer.com': 'https://favicon.is/wetransfer.com',
  'www.wetransfer.com': 'https://favicon.is/wetransfer.com',
  'sendanywhere.com': 'https://favicon.is/sendanywhere.com',
  'www.sendanywhere.com': 'https://favicon.is/sendanywhere.com',
  'filebin.net': 'https://favicon.is/filebin.net',
  'www.filebin.net': 'https://favicon.is/filebin.net',
  'mega.nz': 'https://favicon.is/mega.nz',
  'www.mega.nz': 'https://favicon.is/mega.nz',
  'mega.io': 'https://favicon.is/mega.nz',
  'www.mega.io': 'https://favicon.is/mega.nz',
  'uploadfiles.io': 'https://favicon.is/uploadfiles.io',
  'www.uploadfiles.io': 'https://favicon.is/uploadfiles.io',

  // Cryptocurrency Exchanges
  'ftx.com': 'https://favicon.is/ftx.com',
  'www.ftx.com': 'https://favicon.is/ftx.com',
  'crypto.com': 'https://favicon.is/crypto.com',
  'www.crypto.com': 'https://favicon.is/crypto.com',
  'kucoin.com': 'https://favicon.is/kucoin.com',
  'www.kucoin.com': 'https://favicon.is/kucoin.com',
  'huobi.com': 'https://favicon.is/huobi.com',
  'www.huobi.com': 'https://favicon.is/huobi.com',
  'bybit.com': 'https://favicon.is/bybit.com',
  'www.bybit.com': 'https://favicon.is/bybit.com',
  'bitfinex.com': 'https://favicon.is/bitfinex.com',
  'www.bitfinex.com': 'https://favicon.is/bitfinex.com',
  'okx.com': 'https://favicon.is/okx.com',
  'www.okx.com': 'https://favicon.is/okx.com',

  // Project Management
  'jira.atlassian.com': 'https://favicon.is/atlassian.com',
  'atlassian.com': 'https://favicon.is/atlassian.com',
  'www.atlassian.com': 'https://favicon.is/atlassian.com',
  'confluence.atlassian.com': 'https://favicon.is/atlassian.com',
  'bitbucket.atlassian.com': 'https://favicon.is/atlassian.com',
  'basecamp.com': 'https://favicon.is/basecamp.com',
  'www.basecamp.com': 'https://favicon.is/basecamp.com',
  'clickup.com': 'https://favicon.is/clickup.com',
  'www.clickup.com': 'https://favicon.is/clickup.com',
  'app.clickup.com': 'https://favicon.is/clickup.com',
  'linear.app': 'https://favicon.is/linear.app',
  'www.linear.app': 'https://favicon.is/linear.app',
  'height.app': 'https://favicon.is/height.app',
  'www.height.app': 'https://favicon.is/height.app',

  // Documentation
  'gitbook.com': 'https://favicon.is/gitbook.com',
  'www.gitbook.com': 'https://favicon.is/gitbook.com',
  'app.gitbook.com': 'https://favicon.is/gitbook.com',
  'bookstack.com': 'https://favicon.is/bookstack.com',
  'www.bookstack.com': 'https://favicon.is/bookstack.com',
  'gitiles.com': 'https://favicon.is/gitiles.com',
  'www.gitiles.com': 'https://favicon.is/gitiles.com',
  'slab.com': 'https://favicon.is/slab.com',
  'www.slab.com': 'https://favicon.is/slab.com',
  'coda.io': 'https://favicon.is/coda.io',
  'www.coda.io': 'https://favicon.is/coda.io',

  // Email Marketing
  'convertkit.com': 'https://favicon.is/convertkit.com',
  'www.convertkit.com': 'https://favicon.is/convertkit.com',
  'aweber.com': 'https://favicon.is/aweber.com',
  'www.aweber.com': 'https://favicon.is/aweber.com',
  'getresponse.com': 'https://favicon.is/getresponse.com',
  'www.getresponse.com': 'https://favicon.is/getresponse.com',
  'sendinblue.com': 'https://favicon.is/sendinblue.com',
  'www.sendinblue.com': 'https://favicon.is/sendinblue.com',
  'brevo.com': 'https://favicon.is/brevo.com',
  'www.brevo.com': 'https://favicon.is/brevo.com',
  'activecampaign.com': 'https://favicon.is/activecampaign.com',
  'www.activecampaign.com': 'https://favicon.is/activecampaign.com',

  // Live Streaming
  'obs.live': 'https://favicon.is/obsproject.com',
  'obsproject.com': 'https://favicon.is/obsproject.com',
  'www.obsproject.com': 'https://favicon.is/obsproject.com',
  'streamlabs.com': 'https://favicon.is/streamlabs.com',
  'www.streamlabs.com': 'https://favicon.is/streamlabs.com',
  'streamelements.com': 'https://favicon.is/streamelements.com',
  'www.streamelements.com': 'https://favicon.is/streamelements.com',
  'restream.io': 'https://favicon.is/restream.io',
  'www.restream.io': 'https://favicon.is/restream.io',

  // Domain & Hosting
  'godaddy.com': 'https://favicon.is/godaddy.com',
  'www.godaddy.com': 'https://favicon.is/godaddy.com',
  'namecheap.com': 'https://favicon.is/namecheap.com',
  'www.namecheap.com': 'https://favicon.is/namecheap.com',
  'bluehost.com': 'https://favicon.is/bluehost.com',
  'www.bluehost.com': 'https://favicon.is/bluehost.com',
  'hostgator.com': 'https://favicon.is/hostgator.com',
  'www.hostgator.com': 'https://favicon.is/hostgator.com',
  'siteground.com': 'https://favicon.is/siteground.com',
  'www.siteground.com': 'https://favicon.is/siteground.com',
  'dreamhost.com': 'https://favicon.is/dreamhost.com',
  'www.dreamhost.com': 'https://favicon.is/dreamhost.com',

  // CDN & Performance
  'jsdelivr.com': 'https://favicon.is/jsdelivr.com',
  'www.jsdelivr.com': 'https://favicon.is/jsdelivr.com',
  'cdn.jsdelivr.net': 'https://favicon.is/jsdelivr.com',
  'unpkg.com': 'https://favicon.is/unpkg.com',
  'www.unpkg.com': 'https://favicon.is/unpkg.com',
  'cdnjs.com': 'https://favicon.is/cdnjs.com',
  'www.cdnjs.com': 'https://favicon.is/cdnjs.com',
  'cdnjs.cloudflare.com': 'https://favicon.is/cdnjs.com',

  // API Services
  'postman.com': 'https://favicon.is/postman.com',
  'www.postman.com': 'https://favicon.is/postman.com',
  'web.postman.co': 'https://favicon.is/postman.com',
  'insomnia.rest': 'https://favicon.is/insomnia.rest',
  'www.insomnia.rest': 'https://favicon.is/insomnia.rest',
  'rapidapi.com': 'https://favicon.is/rapidapi.com',
  'www.rapidapi.com': 'https://favicon.is/rapidapi.com',
  'swagger.io': 'https://favicon.is/swagger.io',
  'www.swagger.io': 'https://favicon.is/swagger.io',

  // Database Services
  'mongodb.com': 'https://favicon.is/mongodb.com',
  'www.mongodb.com': 'https://favicon.is/mongodb.com',
  'cloud.mongodb.com': 'https://favicon.is/mongodb.com',
  'planetscale.com': 'https://favicon.is/planetscale.com',
  'www.planetscale.com': 'https://favicon.is/planetscale.com',
  'supabase.com': 'https://favicon.is/supabase.com',
  'www.supabase.com': 'https://favicon.is/supabase.com',
  'app.supabase.com': 'https://favicon.is/supabase.com',
  'firebase.google.com': 'https://favicon.is/firebase.google.com',
  'console.firebase.google.com': 'https://favicon.is/firebase.google.com',
  'fauna.com': 'https://favicon.is/fauna.com',
  'www.fauna.com': 'https://favicon.is/fauna.com',

  // Testing & Monitoring
  'sentry.io': 'https://favicon.is/sentry.io',
  'www.sentry.io': 'https://favicon.is/sentry.io',
  'app.sentry.io': 'https://favicon.is/sentry.io',
  'bugsnag.com': 'https://favicon.is/bugsnag.com',
  'www.bugsnag.com': 'https://favicon.is/bugsnag.com',
  'rollbar.com': 'https://favicon.is/rollbar.com',
  'www.rollbar.com': 'https://favicon.is/rollbar.com',
  'datadog.com': 'https://favicon.is/datadoghq.com',
  'www.datadoghq.com': 'https://favicon.is/datadoghq.com',
  'app.datadoghq.com': 'https://favicon.is/datadoghq.com',
  'newrelic.com': 'https://favicon.is/newrelic.com',
  'www.newrelic.com': 'https://favicon.is/newrelic.com',
  'one.newrelic.com': 'https://favicon.is/newrelic.com',

  // Version Control
  'gitlab.io': 'https://favicon.is/gitlab.com',
  'about.gitlab.io': 'https://favicon.is/gitlab.com',
  'pages.github.com': 'https://favicon.is/github.com',
  'pages.github.io': 'https://favicon.is/github.com',
  'gist.github.com': 'https://favicon.is/github.com',
  'raw.githubusercontent.com': 'https://favicon.is/github.com',
  'github.io': 'https://favicon.is/github.com',

  // Package Managers
  'npmjs.com': 'https://favicon.is/npmjs.com',
  'www.npmjs.com': 'https://favicon.is/npmjs.com',
  'yarnpkg.com': 'https://favicon.is/yarnpkg.com',
  'www.yarnpkg.com': 'https://favicon.is/yarnpkg.com',
  'pypi.org': 'https://favicon.is/pypi.org',
  'www.pypi.org': 'https://favicon.is/pypi.org',
  'packagist.org': 'https://favicon.is/packagist.org',
  'www.packagist.org': 'https://favicon.is/packagist.org',
  'rubygems.org': 'https://favicon.is/rubygems.org',
  'www.rubygems.org': 'https://favicon.is/rubygems.org',
  'nuget.org': 'https://favicon.is/nuget.org',
  'www.nuget.org': 'https://favicon.is/nuget.org',

  // Online Editors
  'jsfiddle.net': 'https://favicon.is/jsfiddle.net',
  'www.jsfiddle.net': 'https://favicon.is/jsfiddle.net',
  'jsbin.com': 'https://favicon.is/jsbin.com',
  'www.jsbin.com': 'https://favicon.is/jsbin.com',
  'plnkr.co': 'https://favicon.is/plnkr.co',
  'www.plnkr.co': 'https://favicon.is/plnkr.co',
  'regex101.com': 'https://favicon.is/regex101.com',
  'www.regex101.com': 'https://favicon.is/regex101.com',
  'regexr.com': 'https://favicon.is/regexr.com',
  'www.regexr.com': 'https://favicon.is/regexr.com',

  // Stock Trading
  'fidelity.com': 'https://favicon.is/fidelity.com',
  'www.fidelity.com': 'https://favicon.is/fidelity.com',
  'schwab.com': 'https://favicon.is/schwab.com',
  'www.schwab.com': 'https://favicon.is/schwab.com',
  'etrade.com': 'https://favicon.is/etrade.com',
  'www.etrade.com': 'https://favicon.is/etrade.com',
  'tdameritrade.com': 'https://favicon.is/tdameritrade.com',
  'www.tdameritrade.com': 'https://favicon.is/tdameritrade.com',
  'interactivebrokers.com': 'https://favicon.is/interactivebrokers.com',
  'www.interactivebrokers.com': 'https://favicon.is/interactivebrokers.com',

  // Religious & Spiritual
  'bible.com': 'https://favicon.is/bible.com',
  'www.bible.com': 'https://favicon.is/bible.com',
  'biblegateway.com': 'https://favicon.is/biblegateway.com',
  'www.biblegateway.com': 'https://favicon.is/biblegateway.com',
  'biblehub.com': 'https://favicon.is/biblehub.com',
  'www.biblehub.com': 'https://favicon.is/biblehub.com',
  'vatican.va': 'https://favicon.is/vatican.va',
  'www.vatican.va': 'https://favicon.is/vatican.va',

  // Miscellaneous Tools
  'speedtest.net': 'https://favicon.is/speedtest.net',
  'www.speedtest.net': 'https://favicon.is/speedtest.net',
  'fast.com': 'https://favicon.is/fast.com',
  'www.fast.com': 'https://favicon.is/fast.com',
  'downforeveryoneorjustme.com': 'https://favicon.is/downforeveryoneorjustme.com',
  'www.downforeveryoneorjustme.com': 'https://favicon.is/downforeveryoneorjustme.com',
  'isitdownrightnow.com': 'https://favicon.is/isitdownrightnow.com',
  'www.isitdownrightnow.com': 'https://favicon.is/isitdownrightnow.com',
  'whatismyipaddress.com': 'https://favicon.is/whatismyipaddress.com',
  'www.whatismyipaddress.com': 'https://favicon.is/whatismyipaddress.com',
  'ipinfo.io': 'https://favicon.is/ipinfo.io',
  'www.ipinfo.io': 'https://favicon.is/ipinfo.io',

  // Text & PDF Tools
  'grammarly.com': 'https://favicon.is/grammarly.com',
  'www.grammarly.com': 'https://favicon.is/grammarly.com',
  'app.grammarly.com': 'https://favicon.is/grammarly.com',
  'hemingwayapp.com': 'https://favicon.is/hemingwayapp.com',
  'www.hemingwayapp.com': 'https://favicon.is/hemingwayapp.com',
  'app.hemingwayapp.com': 'https://favicon.is/hemingwayapp.com',
  'pastebin.com': 'https://favicon.is/pastebin.com',
  'www.pastebin.com': 'https://favicon.is/pastebin.com',
  'hastebin.com': 'https://favicon.is/hastebin.com',
  'www.hastebin.com': 'https://favicon.is/hastebin.com',
  'bin.gy': 'https://favicon.is/bin.gy',
  'www.bin.gy': 'https://favicon.is/bin.gy',
  'smallpdf.com': 'https://favicon.is/smallpdf.com',
  'www.smallpdf.com': 'https://favicon.is/smallpdf.com',
  'ilovepdf.com': 'https://favicon.is/ilovepdf.com',
  'www.ilovepdf.com': 'https://favicon.is/ilovepdf.com',

  // Image Tools
  'tinypng.com': 'https://favicon.is/tinypng.com',
  'www.tinypng.com': 'https://favicon.is/tinypng.com',
  'remove.bg': 'https://favicon.is/remove.bg',
  'www.remove.bg': 'https://favicon.is/remove.bg',
  'photopea.com': 'https://favicon.is/photopea.com',
  'www.photopea.com': 'https://favicon.is/photopea.com',
  'pixlr.com': 'https://favicon.is/pixlr.com',
  'www.pixlr.com': 'https://favicon.is/pixlr.com',
  'photoshop.adobe.com': 'https://favicon.is/adobe.com',
  'compressor.io': 'https://favicon.is/compressor.io',
  'www.compressor.io': 'https://favicon.is/compressor.io',

  // Color Tools
  'coolors.co': 'https://favicon.is/coolors.co',
  'www.coolors.co': 'https://favicon.is/coolors.co',
  'colorhunt.co': 'https://favicon.is/colorhunt.co',
  'www.colorhunt.co': 'https://favicon.is/colorhunt.co',
  'paletton.com': 'https://favicon.is/paletton.com',
  'www.paletton.com': 'https://favicon.is/paletton.com',
  'color.adobe.com': 'https://favicon.is/adobe.com',
  'www.color.adobe.com': 'https://favicon.is/adobe.com',

  // Alternative to Popular Services
  'duckduckgo.com': 'https://favicon.is/duckduckgo.com',
  'proton.me': 'https://favicon.is/proton.me',
  'www.proton.me': 'https://favicon.is/proton.me',
  'brave.com': 'https://favicon.is/brave.com',
  'www.brave.com': 'https://favicon.is/brave.com',
  'vivaldi.com': 'https://favicon.is/vivaldi.com',
  'www.vivaldi.com': 'https://favicon.is/vivaldi.com',
  'opera.com': 'https://favicon.is/opera.com',
  'www.opera.com': 'https://favicon.is/opera.com',
  'firefox.com': 'https://favicon.is/firefox.com',
  'www.firefox.com': 'https://favicon.is/firefox.com',
  'mozilla.org': 'https://favicon.is/mozilla.org',
  'www.mozilla.org': 'https://favicon.is/mozilla.org',

  // Job Platforms
  'monster.com': 'https://favicon.is/monster.com',
  'www.monster.com': 'https://favicon.is/monster.com',
  'careerbuilder.com': 'https://favicon.is/careerbuilder.com',
  'www.careerbuilder.com': 'https://favicon.is/careerbuilder.com',
  'ziprecruiter.com': 'https://favicon.is/ziprecruiter.com',
  'www.ziprecruiter.com': 'https://favicon.is/ziprecruiter.com',
  'dice.com': 'https://favicon.is/dice.com',
  'www.dice.com': 'https://favicon.is/dice.com',
  'flexjobs.com': 'https://favicon.is/flexjobs.com',
  'www.flexjobs.com': 'https://favicon.is/flexjobs.com',
  'remote.co': 'https://favicon.is/remote.co',
  'www.remote.co': 'https://favicon.is/remote.co',
  'remotework.com': 'https://favicon.is/remotework.com',
  'www.remotework.com': 'https://favicon.is/remotework.com',
  'weworkremotely.com': 'https://favicon.is/weworkremotely.com',
  'www.weworkremotely.com': 'https://favicon.is/weworkremotely.com',

  // International Domains
  'google.fr': 'https://favicon.is/google.com',
  'google.de': 'https://favicon.is/google.com',
  'google.es': 'https://favicon.is/google.com',
  'google.it': 'https://favicon.is/google.com',
  'google.co.uk': 'https://favicon.is/google.com',
  'google.ca': 'https://favicon.is/google.com',
  'google.com.au': 'https://favicon.is/google.com',
  'google.co.jp': 'https://favicon.is/google.com',
  'google.co.in': 'https://favicon.is/google.com',
  'google.com.br': 'https://favicon.is/google.com',
  'facebook.fr': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'facebook.de': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'facebook.es': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'facebook.it': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'youtube.fr': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'youtube.de': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'youtube.es': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'youtube.it': 'https://linktree.sirv.com/Images/brands/youtube.svg',
};
  


export function getCompanyFromUrl(chosenData) {
  for (const url in baseUrlIcons) {
    if (chosenData === url) {
      const companyName = baseUrlIcons[url].match(/\/brands\/([^\/]+)\.svg$/);
      return companyName ? companyName[1] : null;
    }
  }
  return null;
}  