// Function to get translated AddContents array
export const getAddContents = (t) => [
    {src: "https://linktree.sirv.com/Images/brands/music.svg", alt: "music", title: t("brandLinks.music"), p: t("brandLinks.music_description")},
    {src: "https://linktree.sirv.com/Images/brands/video.svg", alt: "video", title: t("brandLinks.video"), p: t("brandLinks.video_description")},
    {src: "https://linktree.sirv.com/Images/brands/header.svg", alt: "header", title: t("brandLinks.header"), p: t("brandLinks.header_description")},
    {src: "https://linktree.sirv.com/Images/brands/youtube.svg", alt: "youtube", title: t("brandLinks.youtube"), p: t("brandLinks.youtube_description")},
    {src: "https://linktree.sirv.com/Images/brands/spotify.svg", alt: "spotify", title: t("brandLinks.spotify"), p: t("brandLinks.spotify_description")},
    {src: "https://linktree.sirv.com/Images/brands/pinterest.svg", alt: "pinterest", title: t("brandLinks.pinterest"), p: t("brandLinks.pinterest_description")},
    {src: "https://linktree.sirv.com/Images/brands/twitter.svg", alt: "twitter", title: t("brandLinks.twitter"), p: t("brandLinks.twitter_description")},
    {src: "https://linktree.sirv.com/Images/brands/reddit.svg", alt: "reddit", title: t("brandLinks.reddit"), p: t("brandLinks.reddit_description")},
    {src: "https://linktree.sirv.com/Images/brands/tiktok.svg", alt: "tiktok", title: t("brandLinks.tiktok_profile"), p: t("brandLinks.tiktok_description")},
    {src: "https://linktree.sirv.com/Images/brands/audiomack.svg", alt: "audiomack", title: t("brandLinks.audiomack"), p: t("brandLinks.audiomack_description")},
];


export const baseUrlIcons = {
  'vm.tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'www.tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'm.tiktok.com': 'https://linktree.sirv.com/Images/brands/tiktok.svg',
  'audiomack.com': 'https://linktree.sirv.com/Images/brands/audiomack.svg',
  'www.audiomack.com': 'https://linktree.sirv.com/Images/brands/audiomack.svg',
  'twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'www.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'mobile.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'es.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'fr.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'jp.twitter.com': 'https://linktree.sirv.com/Images/brands/twitter.svg',
  'github.com': 'https://linktree.sirv.com/Images/brands/github.svg',
  'www.github.com': 'https://linktree.sirv.com/Images/brands/github.svg',
  'www.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'in.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'fr.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'es.linkedin.com': 'https://linktree.sirv.com/Images/brands/linkedin.svg',
  'open.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'play.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'i.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'd.spotify.com': 'https://linktree.sirv.com/Images/brands/spotify.svg',
  'www.youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'm.youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'studio.youtube.com': 'https://linktree.sirv.com/Images/brands/youtube.svg',
  'www.reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'old.reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'new.reddit.com': 'https://linktree.sirv.com/Images/brands/reddit.svg',
  'www.paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'www.sandbox.paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'sandbox.paypal.com': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'www.paypal.me': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'paypal.me': 'https://linktree.sirv.com/Images/brands/paypal.svg',
  'www.instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'i.instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'm.instagram.com': 'https://linktree.sirv.com/Images/brands/instagram.svg',
  'www.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'web.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'mobile.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'i.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'm.facebook.com': 'https://linktree.sirv.com/Images/brands/facebook.svg',
  'tr.ee': 'https://linktree.sirv.com/Images/brands/Linktree.svg',
  'www.linktr.ee': 'https://linktree.sirv.com/Images/brands/Linktree.svg',
  'linktr.ee': 'https://linktree.sirv.com/Images/brands/Linktree.svg',
  'www.threads.net': 'https://linktree.sirv.com/Images/brands/Threads.svg',
  'threads.net': 'https://linktree.sirv.com/Images/brands/Threads.svg',
  'wa.me': 'https://linktree.sirv.com/Images/brands/whatsapp.svg',
  'wa.link': 'https://linktree.sirv.com/Images/brands/whatsapp.svg',
  'web.whatsapp.com': 'https://linktree.sirv.com/Images/brands/whatsapp.svg',
  'co.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'www.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'www.pinterest.co.uk': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'in.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'www.pinterest.ca': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'br.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'au.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'fr.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'mx.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'de.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'es.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'it.pinterest.com': 'https://linktree.sirv.com/Images/brands/pinterest.svg',
  'medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'co.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'www.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'www.medium.co.uk': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'in.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'www.medium.ca': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'br.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'au.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'fr.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'mx.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'de.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'es.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'it.medium.com': 'https://linktree.sirv.com/Images/brands/medium.svg',
  'fabiconcept.online': 'https://linktree.sirv.com/Images/icons/me.gif',
};


export function getCompanyFromUrl(chosenData) {
  for (const url in baseUrlIcons) {
    if (chosenData === url) {
      const companyName = baseUrlIcons[url].match(/\/brands\/([^\/]+)\.svg$/);
      return companyName ? companyName[1] : null;
    }
  }
  return null;
}  